### ISSUE TITLE
Demo文字乱码

### ISSUE THREAD

**Issue by shengruqing** [akof1314/Unity-TextMeshPro-DynamicText#1]
![QQ截图20200619105221](https://user-images.githubusercontent.com/13058447/85091878-0ff81880-b21b-11ea-86e7-4323c5a41a0f.jpg)

**Comment by akof1314** [comment]
Demo是为了测试两个控件交替显隐时的重新生成字体贴图

**Comment by lurenzhangdeshuai** [comment]
这不会增加很多drawcall吗

**Comment by akof1314** [comment]
> 这不会增加很多drawcall吗

不会的，几个回调字体几个DC，这是避免不了

**Comment by lingyun5905** [comment]
我这个版本有bug  没有动态生成1.41

**Comment by akof1314** [comment]
@lingyun5905 用新版的，自带了多个贴图
